name: indusmes
base: core22 
version: '0.1'
summary: manufacturing execution system for IndusWorks
description: |
  This application is a manufacturing execution system for IndusWorks.
  This application is meant to be run on Raspberry Pi 5.

grade: devel 
confinement: devmode 

parts:
  indusmes:
    plugin: python
    source: src

apps:
  indusmes:
    command: $SNAP/indusmes/main.py